### ISSUE TITLE
Make keyring use optional

### ISSUE THREAD

**Issue by vituri** [mrchypark/sendgridr#48]
I have many shinyapps and jobs where I need to send emails using `sendgridr`. In the previous versions, I just had to set the `SENDGRID_API` environment variable to my key, and the function `send` would get the key from there. In the new release it is not possible any more, and there is the need to use the prompt to type the password to the keyring. I suggest the following: if the user has the envvar `SENDGRID_API` set, use that; otherwise, use keyring.

I can make a pull request with that, if you wish! I suggest something like this:

```
send = function(mail) {
  tar <- "https://api.sendgrid.com/v3/mail/send"
  
  key = Sys.getenv("SENDGRID_API")
  if (nchar(key) == 0) key = auth_key()
  
  ahd <- httr::add_headers(Authorization = paste0("Bearer ", key), `content-type` = "application/json")
  body <- jsonlite::toJSON(mail, auto_unbox = TRUE)
  body <- gsub("personalizations\":", "personalizations\":[", 
               body)
  body <- gsub("},\"subject\"", "}],\"subject\"", body)
  res <- httr::POST(tar, ahd, body = body)
  res <- httr::content(res)
  if (identical(res, raw(0))) {
    res <- list(success = "Send Success!")
  }
  return(res)
}
```

**Comment by mrchypark** [comment]
Good idea! I'll be working on it soon.

**Comment by agronomofiorentini** [comment]
I agree with @vituri, it would be wonderful if you can use auth_set or auth_check function with api key defined inside .Renviron so we can automatically send emails in shinyapps without using keyring R package

**Comment by mrchypark** [comment]
I will add `apikey` param on `auth_set()` for use `Sys.getenv("SENDGRID_API")`. `auth_set()` will work like before. but with param like `auth_set(Sys.getenv("SENDGRID_API"))`, use input without prompt.

**Comment by agronomofiorentini** [comment]
Thanks @mrchypark.

Let know us when is done and we will test it and report to you if is working.

Thanks again for the effort.

**Comment by wmay** [comment]
I don't think this issue is closed. The function still attempts to use the keyring, even when the API key is provided with an environment variable.

I haven't been able to get this working in a container, even after digging through the source code of 3 different packages and setting options to work around various issues.

The package `keyring` seems to be incompatible with servers/containers and automated scripts more generally. That's because it relies on askpass for users to interactively enter a password to unlock the keyring. Maybe that's fine for the keyring package, because many servers don't have keyrings anyway, so that situation simply isn't relevant to that package.

But it means sendgridr is incapable of automating emails. In order for sendgridr to work non-interactively, there needs to be an option where keyring is not used _at all_.

I can't overstate how much needless frustration the use of the `keyring` package is causing. It seems to be completely inappropriate for any non-interactive use, and is making sendgridr unusable.

_Edit:_ I spoke a bit too soon. This applies to the file backend for keyring. I finally had some luck switching to the "env" backend. Just set `options(keyring_backend = "env")`. That seems to work.
